#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinNativeFullDemo.Droid.Resource", IsApplication=true)]

namespace XamarinNativeFullDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::XamarinNativeFullDemo.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::XamarinNativeFullDemo.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::XamarinNativeFullDemo.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f01000b
			public const int swipeActionLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int swipeActionRight = 2130771980;
			
			// aapt resource value: 0x7f010004
			public const int swipeAnimationTime = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int swipeBackView = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int swipeCloseAllItemsWhenMoveList = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int swipeDrawableChecked = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int swipeDrawableUnchecked = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int swipeFrontView = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int swipeMode = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int swipeOffsetLeft = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int swipeOffsetRight = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int swipeOpenOnLongPress = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080001
			public const int black = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int light_grey = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int materialGrey = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int red = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int white = 2131230722;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int delete_margin = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int row_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int row_text_size = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int search_padding = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int search_radius = 2131296259;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int adidas = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_bordered = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bershka = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_bordered = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int colins = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int columbia = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cropp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int default_account = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int edit_text_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int general = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int house = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_info = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int jacket = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int jacket_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int levis = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ltb = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mango = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int massimo_dutti = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int new_balance = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int next = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int nike = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ostin = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pants = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pants_icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pull_and_bear = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int puma = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int reebok = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int reserved = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int right_button_border = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int search_rounded = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int shirt = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int shirt_icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int shoes = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int shoes_icon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int single_border = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sinsay = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int size_female = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int size_female_fit = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int size_mail_fit = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int sizes = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int solid_shape = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int springfield = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int stradivarius = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int sweater = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int sweater_icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int terranova = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int textedit_bordered = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int timberland = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int topsecret = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int tshirt = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int tshirt_icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int waikiki = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int zara = 2130837556;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000a
			public const int accountList = 2131427338;
			
			// aapt resource value: 0x7f0b000d
			public const int adView = 2131427341;
			
			// aapt resource value: 0x7f0b0000
			public const int both = 2131427328;
			
			// aapt resource value: 0x7f0b001f
			public const int btnCancelCalc = 2131427359;
			
			// aapt resource value: 0x7f0b0010
			public const int btnInfo = 2131427344;
			
			// aapt resource value: 0x7f0b001e
			public const int btnSaveCalc = 2131427358;
			
			// aapt resource value: 0x7f0b000e
			public const int calc_activity = 2131427342;
			
			// aapt resource value: 0x7f0b0004
			public const int choice = 2131427332;
			
			// aapt resource value: 0x7f0b002a
			public const int contentFrame = 2131427370;
			
			// aapt resource value: 0x7f0b000b
			public const int ct1 = 2131427339;
			
			// aapt resource value: 0x7f0b0026
			public const int ct1Text = 2131427366;
			
			// aapt resource value: 0x7f0b000c
			public const int ct1_back = 2131427340;
			
			// aapt resource value: 0x7f0b0005
			public const int dismiss = 2131427333;
			
			// aapt resource value: 0x7f0b0013
			public const int imgFit = 2131427347;
			
			// aapt resource value: 0x7f0b0021
			public const int imgLogo = 2131427361;
			
			// aapt resource value: 0x7f0b0023
			public const int imgNext = 2131427363;
			
			// aapt resource value: 0x7f0b0001
			public const int left = 2131427329;
			
			// aapt resource value: 0x7f0b0020
			public const int linearLayout = 2131427360;
			
			// aapt resource value: 0x7f0b0007
			public const int main_activity = 2131427335;
			
			// aapt resource value: 0x7f0b002c
			public const int menu_add = 2131427372;
			
			// aapt resource value: 0x7f0b002b
			public const int menu_edit = 2131427371;
			
			// aapt resource value: 0x7f0b002e
			public const int menu_import = 2131427374;
			
			// aapt resource value: 0x7f0b002d
			public const int menu_new = 2131427373;
			
			// aapt resource value: 0x7f0b0002
			public const int none = 2131427330;
			
			// aapt resource value: 0x7f0b001d
			public const int reLayBottom = 2131427357;
			
			// aapt resource value: 0x7f0b0012
			public const int reLayCenter = 2131427346;
			
			// aapt resource value: 0x7f0b000f
			public const int reLayTop = 2131427343;
			
			// aapt resource value: 0x7f0b0006
			public const int reveal = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int right = 2131427331;
			
			// aapt resource value: 0x7f0b0009
			public const int searchView = 2131427337;
			
			// aapt resource value: 0x7f0b001c
			public const int swFemale = 2131427356;
			
			// aapt resource value: 0x7f0b0008
			public const int toolbar = 2131427336;
			
			// aapt resource value: 0x7f0b0029
			public const int toolbar_title = 2131427369;
			
			// aapt resource value: 0x7f0b0016
			public const int txtA = 2131427350;
			
			// aapt resource value: 0x7f0b0025
			public const int txtActionDelete = 2131427365;
			
			// aapt resource value: 0x7f0b0024
			public const int txtActionExport = 2131427364;
			
			// aapt resource value: 0x7f0b0017
			public const int txtB = 2131427351;
			
			// aapt resource value: 0x7f0b001a
			public const int txtC = 2131427354;
			
			// aapt resource value: 0x7f0b0014
			public const int txtD = 2131427348;
			
			// aapt resource value: 0x7f0b0019
			public const int txtE = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int txtF = 2131427352;
			
			// aapt resource value: 0x7f0b0015
			public const int txtG = 2131427349;
			
			// aapt resource value: 0x7f0b001b
			public const int txtH = 2131427355;
			
			// aapt resource value: 0x7f0b0022
			public const int txtName = 2131427362;
			
			// aapt resource value: 0x7f0b0028
			public const int txtSize = 2131427368;
			
			// aapt resource value: 0x7f0b0027
			public const int txtTypeId = 2131427367;
			
			// aapt resource value: 0x7f0b0011
			public const int txtUserName = 2131427345;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Accounts = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int banner = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Calculation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CT1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int CT1Action = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int CT1Text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int toolbar = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int zxingscanneractivitylayout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int zxingscannerfragmentlayout = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int edit_menu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int main_menu = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int popup_menu = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int add = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int back = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int clear = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int edit = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Icon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int next = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int save = 2130903046;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070021
			public const int CLOTHES_JACKET = 2131165217;
			
			// aapt resource value: 0x7f070026
			public const int CLOTHES_PANTS = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int CLOTHES_SHIRT = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int CLOTHES_SHOES = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int CLOTHES_SWEATER = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int CLOTHES_T_SHIRT = 2131165218;
			
			// aapt resource value: 0x7f070036
			public const int MESSAGE_ACCOUNT_LIMIT = 2131165238;
			
			// aapt resource value: 0x7f07001e
			public const int MESSAGE_ALPHABETIC_LENGTH = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int MESSAGE_ALPHABETIC_PATTERN = 2131165213;
			
			// aapt resource value: 0x7f07002f
			public const int MESSAGE_CHECK_CONNECTION = 2131165231;
			
			// aapt resource value: 0x7f070016
			public const int MESSAGE_DELETE = 2131165206;
			
			// aapt resource value: 0x7f07001f
			public const int MESSAGE_DUBLICATED_ACCOUNT = 2131165215;
			
			// aapt resource value: 0x7f070035
			public const int MESSAGE_EDIT_WARNING = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int MESSAGE_IMPORT_ERROR = 2131165234;
			
			// aapt resource value: 0x7f070015
			public const int MESSAGE_INFO = 2131165205;
			
			// aapt resource value: 0x7f070033
			public const int MESSAGE_LOAD_DATA = 2131165235;
			
			// aapt resource value: 0x7f070030
			public const int MESSAGE_LOAD_ERROR = 2131165232;
			
			// aapt resource value: 0x7f070019
			public const int MESSAGE_MAX_LENGTH = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int MESSAGE_MAX_VALUE = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int MESSAGE_MIN_LENGTH = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int MESSAGE_MIN_VALUE = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int MESSAGE_NUMERIC_PATTERN = 2131165212;
			
			// aapt resource value: 0x7f070017
			public const int MESSAGE_REQUIRED = 2131165207;
			
			// aapt resource value: 0x7f070031
			public const int MESSAGE_SCAN_CODE = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int MESSAGE_SELECT_ACCOUNT = 2131165236;
			
			// aapt resource value: 0x7f070020
			public const int MESSAGE_UNEXISTING_SIZE = 2131165216;
			
			// aapt resource value: 0x7f070027
			public const int TITLE_DELETE = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int TITLE_ERROR = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int TITLE_INFO = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int UserName = 2131165226;
			
			// aapt resource value: 0x7f07000c
			public const int a_size = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int account_title = 2131165188;
			
			// aapt resource value: 0x7f07002e
			public const int add_account = 2131165230;
			
			// aapt resource value: 0x7f070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int b_size = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int c_size = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int cancel = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_unknown_issue = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int d_size = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int delete = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int delete_percent = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int e_size = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int edit = 2131165191;
			
			// aapt resource value: 0x7f07002d
			public const int export_account = 2131165229;
			
			// aapt resource value: 0x7f070011
			public const int f_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int g_size = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int h_size = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int hello = 2131165185;
			
			// aapt resource value: 0x7f07002c
			public const int import_account = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int new_account = 2131165227;
			
			// aapt resource value: 0x7f07000a
			public const int ok = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int save = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int search_text = 2131165204;
			
			// aapt resource value: 0x7f070037
			public const int test_banner_ad_unit_id = 2131165239;
			
			// aapt resource value: 0x7f070003
			public const int test_title = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int uname_hint = 2131165195;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_IAPTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int iosTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] SwipeListView = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 8
			public const int SwipeListView_swipeActionLeft = 8;
			
			// aapt resource value: 9
			public const int SwipeListView_swipeActionRight = 9;
			
			// aapt resource value: 1
			public const int SwipeListView_swipeAnimationTime = 1;
			
			// aapt resource value: 6
			public const int SwipeListView_swipeBackView = 6;
			
			// aapt resource value: 4
			public const int SwipeListView_swipeCloseAllItemsWhenMoveList = 4;
			
			// aapt resource value: 10
			public const int SwipeListView_swipeDrawableChecked = 10;
			
			// aapt resource value: 11
			public const int SwipeListView_swipeDrawableUnchecked = 11;
			
			// aapt resource value: 5
			public const int SwipeListView_swipeFrontView = 5;
			
			// aapt resource value: 7
			public const int SwipeListView_swipeMode = 7;
			
			// aapt resource value: 2
			public const int SwipeListView_swipeOffsetLeft = 2;
			
			// aapt resource value: 3
			public const int SwipeListView_swipeOffsetRight = 3;
			
			// aapt resource value: 0
			public const int SwipeListView_swipeOpenOnLongPress = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
